import type { Exercise } from '@/modules/exercises';

export const pythonExercises: Exercise[] = [
  { id: 'soma-dois-numeros', tipo: 'codigo', titulo: 'Some dois números', enunciado: 'Crie uma função que receba dois números e retorne a soma deles.', topico: 'Funções', dificuldade: 'facil', xp: 10, dicas: ['Defina uma função com dois parâmetros.', 'Use o operador +.', 'Retorne a expressão a + b.'], solucao: 'def somar(a, b):\n    return a + b', tags: ['função', 'aritmética'], aulaRelacionada: 'funcoes', nomeFuncao: 'somar', starterCode: 'def somar(a, b):\n    # escreva sua solução\n    pass', testes: [{ entrada: '2, 3', esperado: '5' }, { entrada: '-1, 4', esperado: '3' }, { entrada: '10, 5', esperado: '15', oculto: true }] },
  { id: 'completar-pares', tipo: 'completar', titulo: 'Complete a lista de pares', enunciado: 'Preencha a lacuna para filtrar apenas números pares.', topico: 'List comprehensions', dificuldade: 'facil', xp: 10, dicas: ['O resto da divisão por 2 identifica pares.', 'Use o operador %.','A condição deve ser x % 2 == 0.'], solucao: 'pares = [x for x in numeros if x % 2 == 0]', tags: ['listas'], starterCode: 'numeros = [1, 2, 3, 4, 5, 6]\npares = [x for x in numeros if ___]\nprint(pares)', testes: [{ entrada: '', esperado: '[2, 4, 6]' }] },
  { id: 'corrija-o-loop', tipo: 'bug', titulo: 'Corrija o loop', enunciado: 'Corrija o erro para que a função retorne a soma de 1 até n.', topico: 'Laços', dificuldade: 'medio', xp: 20, dicas: ['O acumulador precisa começar em zero.', 'range não inclui o limite final.', 'Use range(1, n + 1).'], solucao: 'def soma_ate(n):\n    total = 0\n    for valor in range(1, n + 1):\n        total += valor\n    return total', tags: ['for', 'debug'], starterCode: 'def soma_ate(n):\n    total = 1\n    for valor in range(1, n):\n        total += valor\n    return total', nomeFuncao: 'soma_ate', testes: [{ entrada: '5', esperado: '15' }, { entrada: '1', esperado: '1', oculto: true }] },
  { id: 'qual-e-a-saida', tipo: 'multipla-escolha', titulo: 'Qual é a saída?', enunciado: 'Observe o código e escolha o resultado impresso.', topico: 'Fundamentos', dificuldade: 'facil', xp: 10, dicas: ['A função dobra o valor recebido.', 'A chamada usa 4 como argumento.'], solucao: '8', tags: ['funções'], starterCode: 'def dobro(x):\n    return x * 2\n\nprint(dobro(4))', alternativas: [{ texto: '4', correta: false, explicacao: 'O valor é multiplicado por 2.' }, { texto: '8', correta: true, explicacao: '4 vezes 2 resulta em 8.' }, { texto: '6', correta: false, explicacao: 'Não há soma no código.' }] },
  { id: 'ordene-o-programa', tipo: 'ordenar', titulo: 'Ordene o programa', enunciado: 'Reordene as linhas para calcular e exibir o dobro.', topico: 'Sintaxe', dificuldade: 'medio', xp: 20, dicas: ['A função deve existir antes da chamada.', 'Depois defina o resultado.', 'Por fim, use print.'], solucao: 'def dobro(x):\n    return x * 2\nresultado = dobro(5)\nprint(resultado)', tags: ['ordenação'], linhas: ['print(resultado)', 'resultado = dobro(5)', '    return x * 2', 'def dobro(x):'], ordemCorreta: ['def dobro(x):', '    return x * 2', 'resultado = dobro(5)', 'print(resultado)'] },
  { id: 'preveja-o-output', tipo: 'prever-saida', titulo: 'Preveja a saída', enunciado: 'Digite exatamente o que será impresso pelo código.', topico: 'Listas', dificuldade: 'facil', xp: 10, dicas: ['A lista começa em zero.', 'pop remove o último item.'], solucao: '[1, 2]', tags: ['listas'], starterCode: 'itens = [1, 2, 3]\nitens.pop()\nprint(itens)', saidaEsperada: '[1, 2]' },
];

export default pythonExercises;
